export { default as Home } from '../Pages/Home'
export { default as Category } from '../Pages/Category'
export { default as ProductDetails } from '../Pages/ProductDetails'
export { default as Cart } from '../Pages/Cart'
export { default as Checkout } from '../Pages/Checkout'
export { default as gfurniturelogo } from '../Assets/gfurniturelogo.png'
export { default as menuIcon } from '../Assets/drop-down.png'
export { default as hamburger } from '../Assets/hamburger-menu.png'
export { default as cartIcon } from '../Assets/cartIcon.png'
export { default as searchIcon } from '../Assets/searchIcon.png'
export { default as HeroImage1 } from '../Assets/Hero-img-1.png'
export { default as HeroImage2 } from '../Assets/Hero-img-2.png'
export { default as HeroImage3 } from '../Assets/Hero-img-3.png'
export { default as HeadingLayer} from '../Assets/Heading-layer.png'
export { default as FeaturedProductsImg1} from '../Assets/Featured-products-img1.png'
export { default as FeaturedProductsImg2} from '../Assets/Featured-products-img2.png'
export { default as FeaturedProductsImg3} from '../Assets/Featured-products-img3.png'
export { default as FeaturedProductsImg4} from '../Assets/Featured-products-img4.png'
export { default as FeaturedProductsImg5} from '../Assets/Featured-products-img5.png'
export { default as FeaturedProductsImg6} from '../Assets/Featured-products-img6.png'
export { default as FeaturedProductsImg7} from '../Assets/Featured-products-img7.png'
export { default as FeaturedProductsImg8} from '../Assets/Featured-products-img8.png'
export { default as FeaturedProductsImg9} from '../Assets/ProductImage9.png'
export { default as FeaturedProductsImg10} from '../Assets/ProductImage10.png'
export { default as FeaturedProductsImg11} from '../Assets/ProductImage11.png'
export { default as FeaturedProductsImg12} from '../Assets/ProductImage12.png'
export { default as FeaturedProductsImg13} from '../Assets/ProductImage13.png'
// export { default as FeaturedProductsImg14} from '../Assets/ProductImage14.png'
export { default as FeaturedProductsImg15} from '../Assets/ProductImage15.png'
export { default as TrendsImg1} from '../Assets/trends-img-1.png'
export { default as TrendsImg2} from '../Assets/trends-img-2.png'
export { default as TrendsImg3} from '../Assets/trends-img-3.png'
export { default as AuthorPics} from '../Assets/Author-pics.png'
export { default as paginationArrowright} from '../Assets/pagination-arrow-right.png'
export { default as paginationArrowleft} from '../Assets/pagination-arrow-left.png'
export { default as FashionTrendsImg} from '../Assets/FashionTrendsImg.png'
export { default as SuccessHistoryImage} from '../Assets/SuccessHistoryImage.png'
export { default as ColorOption1} from '../Assets/ColorOption1.png'
export { default as ColorOption2} from '../Assets/ColorOption2.png'
export { default as ColorOption3} from '../Assets/ColorOption3.png'
export { default as ColorOption4} from '../Assets/ColorOption4.png'
export { default as ColorOption5} from '../Assets/ColorOption5.png'
export { default as ColorOption6} from '../Assets/ColorOption6.png'
export { default as ColorOption7} from '../Assets/ColorOption7.png'
export { default as ColorOption8} from '../Assets/ColorOption8.png'
export { default as BoxImage} from '../Assets/BoxImage.png'
export { default as TruckImage} from '../Assets/TruckImage.png'
export { default as HandsImage} from '../Assets/HandsImage.png'